services:
  - type: web
    name: B_P_M_s
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URL
        value: mongodb+srv://raghavnadiminti:Raghav1234@cluster0.kdday.mongodb.net/
      - key: PORT
        value: 5000